- name: "setup {{ component }} server"
  hosts: "{{ component }}"
  become: yes
  roles: # while executing ,ansible connected to mongodb server then calling roles & executing mongodb in roles
  - "{{ component }}"